"""
Init
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9jnerlff23u8ed01np9g6ysbhsh0dvcs'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.String(length=255), nullable=True))